openapi: 3.0.0
info:
  version: 1.0.0
  title: Управление личными финансами
  contact:
    name: ITAcademy
    url: http://it-academy.by

servers:
  - url: http://{host}:{port}
    description: custom server
    variables:
      host:
        description: host name
        default: localhost
      port:
        description: port value
        default: "8080"

tags:
  - name: "Отчёты"
    description: "Построение отчётов по счетам и операциям"

paths:
  /api/v1/report/{type}:
    post:
      tags:
        - "Отчёты"
      summary: "Добавление нового отчёта"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: type
          description: "Тип отчёта"
          required: true
          schema:
            $ref: '#/components/schemas/ReportType'
      requestBody:
        $ref: "#/components/requestBodies/CreateReport"
      responses:
        '201':
          description: Отчёт запущен
        '400':
          $ref: '../../common-lib.yml#/components/responses/Bad_Request'
        '401':
          $ref: '../../common-lib.yml#/components/responses/Unauthorized'
        '403':
          $ref: '../../common-lib.yml#/components/responses/Forbidden'
        '500':
          $ref: '../../common-lib.yml#/components/responses/Internal_Server_Error'
  /api/v1/report:
    get:
      tags:
        - "Отчёты"
      summary: "Получить страницу отчётов"
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
          required: false
        - in: query
          name: size
          schema:
            type: integer
          description: Размер страницы
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfReport'
        '400':
          $ref: '../../common-lib.yml#/components/responses/Bad_Request'
        '401':
          $ref: '../../common-lib.yml#/components/responses/Unauthorized'
        '403':
          $ref: '../../common-lib.yml#/components/responses/Forbidden'
        '500':
          $ref: '../../common-lib.yml#/components/responses/Internal_Server_Error'
  /api/v1/report/{uuid}/export:
    get:
      tags:
        - "Отчёты"
      summary: Скачать сформированный отчёт
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: Идентификатор отчёта
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                format: binary
                description: Файл
          headers:
            Content-Disposition:
              schema:
                type: string
                description: Описание файла
                example: 'attachment; filename="f43b1a97-dc00-40e2-9450-ace8d2416f3d"'
            Content-Type:
              schema:
                type: string
                description: Описание типа контента
                example: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        '204':
          description: Сервер, по предоставленному uuid, не смог найти информацию
        '400':
          $ref: '../../common-lib.yml#/components/responses/Bad_Request'
        '401':
          $ref: '../../common-lib.yml#/components/responses/Unauthorized'
        '403':
          $ref: '../../common-lib.yml#/components/responses/Forbidden'
        '500':
          $ref: '../../common-lib.yml#/components/responses/Internal_Server_Error'
    head:
      tags:
        - "Отчёты"
      summary: Проверка доступности сформированного отчёта
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: Идентификатор отчёта
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: OK
        '204':
          description: Сервер, по предоставленному uuid, не смог найти информацию
        '400':
          $ref: '../../common-lib.yml#/components/responses/Bad_Request'
        '401':
          $ref: '../../common-lib.yml#/components/responses/Unauthorized'
        '403':
          $ref: '../../common-lib.yml#/components/responses/Forbidden'
        '500':
          $ref: '../../common-lib.yml#/components/responses/Internal_Server_Error'


components:
  securitySchemes:
    bearerAuth:
      $ref: '../../common-lib.yml#/components/securitySchemes/bearerAuth'
  requestBodies:
    CreateReport:
      description: Параметры для создания отчёта
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ReportParamBalance'
              - $ref: '#/components/schemas/ReportParamByDate'
              - $ref: '#/components/schemas/ReportParamByCategory'
  schemas:
    Report:
      type: object
      description: Отчёт
      required:
        - description
      allOf:
        - $ref: '../../common-lib.yml#/components/schemas/t_base_essence'
      properties:
        status:
          type: string
          description: |
            Статус отчёта:
              * `LOADED` - Ожидает формирования
              * `PROGRESS` - Формирует
              * `ERROR` - Ошибка формирование
              * `DONE` - Сформирован
          enum:
            - LOADED
            - PROGRESS
            - ERROR
            - DONE
        type:
          $ref: '#/components/schemas/ReportType'
        description:
          type: string
          description: "Описание параметров отчёта в человеческом формате"
          readOnly: true
          example: "Дата совершения операции: 01.01.2021 - 01.01.2022"
        params:
          oneOf:
            - $ref: '#/components/schemas/ReportParamBalance'
            - $ref: '#/components/schemas/ReportParamByDate'
            - $ref: '#/components/schemas/ReportParamByCategory'

    ReportType:
      type: string
      description: |
        Тип отчёта:
          * `BALANCE` - Остатки по счетам
          * `BY_DATE` - Выписка со счёта в разрезе дат
          * `BY_CATEGORY` - Выписка со счёта в разрезе категории
      enum:
        - BALANCE
        - BY_DATE
        - BY_CATEGORY

    ReportParamBalance:
      type: object
      description: Параметры запуска отчёта о балансе
      properties:
        accounts:
          type: array
          description: Аккаунты
          items:
            type: string
            format: uuid

    ReportParamByDate:
      type: object
      description: Параметры запуска отчёта в разрезе даты операции
      properties:
        accounts:
          type: array
          description: Аккаунты
          items:
            type: string
            format: uuid
        from:
          description: Операции начиная с даты
          type: string
          format: date
        to:
          description: Операции заканчивая датой
          type: string
          format: date
        categories:
          type: array
          description: Категории
          items:
            type: string
            format: uuid
    ReportParamByCategory:
      type: object
      description: Параметры запуска отчёта в разрезе категорий
      properties:
        accounts:
          type: array
          description: Аккаунты
          items:
            type: string
            format: uuid
        from:
          description: Операции начиная с даты
          type: string
          format: date
        to:
          description: Операции заканчивая датой
          type: string
          format: date
        categories:
          type: array
          description: Категории
          items:
            type: string
            format: uuid

    PageOfReport:
      type: object
      description: Отчёты
      allOf:
        - $ref: '../../common-lib.yml#/components/schemas/t_page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Report'
